### ISSUE TITLE
Support for GTA San Andreas

### ISSUE THREAD

**Issue by thelink2012** [thelink2012/gta3sc#6]
+ [x] [Arrays](http://www.gtamodding.com/wiki/SCM_language#Arrays)
+ [x] SWITCH (#32)
+ [x] TEXT_LABEL / TEXT_LABEL16  (#33)
+ [x] Streamed scripts (#34)
+ [x] ~~CONST_INT / CONST_FLOAT / CONSTANT_INT~~ (too risky, see #35)
+ [x] Change the amount of allowed local variables, including mission locals (#36)
+ [x] SKIP_CUTSCENE* directives (#37)

Its `commands.xml` also probably needs more static information? (#38)

**Comment by thelink2012** [comment]
Closing this in favor of the individual issues and the milestone.

**Comment by thelink2012** [comment]
Actually, no, as there isn't a way to add two milestones to a single issue.

**Comment by thelink2012** [comment]
Done!
